### ISSUE TITLE
Playhead position moves relative to audio when zooming in

### ISSUE THREAD

**Issue by henrybourne** [pkalogiros/AudioMass#11]
I noticed a problem when you have zoomed in. You set the playhead position then hit play and the view scrolls to keep the current playhead position in view. When this happens the playhead origin (not sure what to call it!) and the current playhead position both move relatively to the audio and become misaligned. 

I initially noticed this as I thought I had dropped the playhead before a transient, but didn't hear it when I hit play. It seems like the playhead and waveform view had become misaligned.

I was editing an mp3 using macOS Safari 13.1.

(fantastic work overall, by the way 👍 very impressive)

**Comment by pkalogiros** [comment]
Thank you so much for your kind words! You can disable this under the "View" menu.

View -> Follow Cursor

video demonstration:
https://pantelis.s3-us-west-2.amazonaws.com/0/audiomass/audiomass-cursor.mp4

Cheers!

**Comment by henrybourne** [comment]
Hi, thanks for the reply. 

I appreciate the clarity, but I don't think I explained the issue very clearly in my first post. Here's a video to help: 

https://youtu.be/Yfm6zAcgwRg 

When **Follow Cursor** is on, you can see the waveform moving at a different speed to the timeline and the playhead start position. I hope that makes sense?

Cheers

**Comment by pkalogiros** [comment]
Ooh, apologies I misunderstood! Yes, this looks wrong. I will investigate further.

Thank you so much for taking the time to report, and of course for getting back with more information! This is super helpful1
