### ISSUE TITLE
Feature Request: Export as wav

### ISSUE THREAD

**Issue by H-man** [pkalogiros/AudioMass#12]
Would it be possible to export files as wav also?

**Comment by ELI7VH** [comment]
wondering about this as well. Is it hard to export wavs from webaudio?

**Comment by pcgardner-ovr** [comment]
I was surprised to be able to read a wav file but then not be able save it back out again. 

Imagine the limitations here are mostly developer bandwidth rather than anything technical. Any requirements you'd need for a pull request?

**Comment by pkalogiros** [comment]
.wav export has been pushed (both in this repo and on audiomass.co).

It is under **File > Export/Download**
<img width="523" alt="Screen Shot 2020-06-12 at 8 03 43 AM" src="https://user-images.githubusercontent.com/1465079/84516893-51208380-ac83-11ea-9cd6-a96656226bbf.png">

**Comment by pkalogiros** [comment]
Closing issue! (weekend cleaning of issues) Feel free to re-open if needed
