### ISSUE TITLE
Feature request: An "undo" history.

### ISSUE THREAD

**Issue by interactiveaudiolab** [pkalogiros/AudioMass#15]
Edits appear to be destructive, without the ability to undo changes.

**Comment by pkalogiros** [comment]
You can undo and redo currently.
The options are under the Edit Menu (Edit -> Undo (action) / Redo (action))

Or you can undo and redo, with the Shift + Z (undo) and Shift + Y (redo) key combos.

Here is a video demonstration!
https://pantelis.s3-us-west-2.amazonaws.com/0/audiomass/audiomass-undo.mp4

**Comment by pkalogiros** [comment]
Will be closing this issue. Please feel free to re-open if things are not right.
