### ISSUE TITLE
Feature Request: Would love an API of this

### ISSUE THREAD

**Issue by adityakrshnn** [pkalogiros/AudioMass#29]
Hi,

It would be totally awesome if you could provide the tool's features as an API served from a single JS file!

**Comment by pkalogiros** [comment]
Hello! Thanks so much for your suggestion. Do you mean that you 'd like a library that can be invoked programatically, so let's say, for setting the volume in a piece of audio, running something like

```AudioEngine.Effects.SetVolume (audio_buffer, volume_levels );```


?

It would certainly be possible, but it would be quite some work before it's ready :) In the meantime you can check out libraries like howler (https://howlerjs.com/). But I would be happy to investigate this more of course
