### ISSUE TITLE
https certificate is invalid on https://audiomass.co/

### ISSUE THREAD

**Issue by gregsadetsky** [pkalogiros/AudioMass#77]
see issue title :-)

https://www.sslshopper.com/ssl-checker.html#hostname=audiomass.co

![image (25)](https://github.com/pkalogiros/AudioMass/assets/1017304/e7f8b66c-57c0-4c70-a634-46d7a304e2ff)
![image (26)](https://github.com/pkalogiros/AudioMass/assets/1017304/79f39240-186c-4b21-8226-e2e47210f135)

Cheers

**Comment by suterma** [comment]
This seems to be solved now, as it's using a Let's encrypt cert, with hopefully automatic update.
Currently, it's valid until Fri, 17 Jan 2025 14:15:36 GMT

**Comment by gregsadetsky** [comment]
Indeed! Thanks

**Comment by kevinW0W** [comment]
well look like it appear again and my anti-virus blocked the webpage and it said certificate expired

**Comment by gregsadetsky** [comment]
yeah same here. the certificate [expired 9 days ago](https://www.sslshopper.com/ssl-checker.html#hostname=audiomass.co)

<img width="517" height="205" alt="Image" src="https://github.com/user-attachments/assets/dbf1dbb2-7207-4e93-99c8-9a3d8f99a652" />

---

@pkalogiros let me know if I can help with hosting, I'd love to offer server space and auto renewing https certificates. your project is amazing, I'd be happy to contribute by taking care of this

cheers!
