### ISSUE TITLE
Dead scrollbars on Linux in the welcome dialog

### ISSUE THREAD

**Issue by city41** [pkalogiros/AudioMass#8]
I believe this is due to using `overflow: scroll` instead of `overflow: auto`

This is on Ubuntu 18 with Chrome.

![image](https://user-images.githubusercontent.com/141159/83175831-8b6a1c80-a0ea-11ea-8c45-6b7cf59bfd22.png)

**Comment by pkalogiros** [comment]
You are 100% correct. ```overflow: auto``` is needed. Thanks a lot for pointing this out :)  
I pushed a fix at ```ee1df65```

and will be deploying on audiomass.co later today!
